export enum nationality {
  Australian = 'Australian',
  British = 'British',
  Canadian = 'Canadian',
  Chinese = 'Chinese',
  Danish = 'Danish',
  Dutch = 'Dutch',
  Finnish = 'Finnish',
  French = 'French',
  Japanese = 'Japanese',
  Monegasque = 'Monegasque',
  Mexican = 'Mexican',
  Spanish = 'Spanish',
  German = 'German',
  Thai = 'Thai',
}

export enum circuits {
  AlbertPark = 'albert_park',
  Americas = 'americas',
  Baku = 'baku',
  Bahrain = 'bahrain',
  Catalunya = 'catalunya',
  Hungaroring = 'hungaroring',
  Interlagos = 'interlagos',
  Imola = 'imola',
  Jeddah = 'jeddah',
  MarinaBay = 'marina_bay',
  Miami = 'miami',
  Monaco = 'monaco',
  Monza = 'monza',
  RedBullRing = 'red_bull_ring',
  Ricard = 'ricard',
  Rodriguez = 'rodriguez',
  Silverstone = 'silverstone',
  Spa = 'spa',
  Suzuka = 'suzuka',
  Villeneuve = 'villeneuve',
  YasMarina = 'yas_marina',
  Zandvoort = 'zandvoort',
}

export enum other {
  Logo = 'LogoF1',
}
