export const CIRCUIT_COUNTRIES = {
  albert_park: 'Bahrain',
  americas: 'USA',
  BAK: 'Azerbaijan',
  bahrain: 'Bahrain',
  catalunya: 'Spain',
  hungaroring: 'Hungary',
  interlagos: 'Brazil',
  imola: 'Italy',
  jeddah: 'Saudi Arabia',
  marina_bay: 'Singapore',
  miami: 'USA',
  monaco: 'Monaco',
  monza: 'Italy',
  red_bull_ring: 'Austria',
  ricard: 'France',
  rodriguez: 'Mexico',
  silverstone: 'United Kingdom',
  spa: 'Belgium',
  suzuka: 'Japan',
  villeneuve: 'Canada',
  yas_marina: 'United Arab Emirate',
  zandvoort: 'Netherlands',
};
