export const DRIVER_NUMBERS = {
  leclerc: 16,
  sainz: 55,
  max_verstappen: 1,
  russell: 63,
  hamilton: 44,
  ocon: 31,
  perez: 11,
  kevin_magnussen: 20,
  bottas: 77,
  norris: 4,
  tsunoda: 22,
  gasly: 10,
  alonso: 14,
  zhou: 22,
  mick_schumacher: 47,
  stroll: 18,
  hulkenberg: 27,
  albon: 23,
  ricciardo: 3,
  latifi: 6,
  vettel: 5,
};
